name: Build and Test library

on:
  - push
  - pull_request

jobs:

  build-and-test-library:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache go dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...
